import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { parseQmdSearchOutput } from '../src/qmd.js';
import { adaptiveSearch } from '../src/search.js';

test('external collection opt-in resolves snippets and enforces collection boundaries and globs', (t) => {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'qmd-external-'));
  t.after(() => fs.rmSync(base, { recursive: true, force: true }));
  const root = path.join(base, 'project');
  const external = path.join(base, 'external');
  fs.mkdirSync(root);
  fs.mkdirSync(external);
  fs.writeFileSync(path.join(external, 'guide.md'), 'external zebra documentation');
  fs.writeFileSync(path.join(root, 'guide.md'), 'local duplicate filename');
  fs.writeFileSync(path.join(base, 'secret.md'), 'secret');
  const mapping = { docs: external };
  const output = 'qmd://docs/guide.md';
  const hits = parseQmdSearchOutput(output, root, mapping);
  assert.equal(hits.length, 1);
  assert.equal(path.resolve(root, hits[0].path), path.join(external, 'guide.md'));
  assert.equal(parseQmdSearchOutput('qmd://docs/../secret.md', root, mapping).length, 0);
  assert.equal(parseQmdSearchOutput('qmd://docs/missing.md', root, mapping).length, 0);
  assert.equal(parseQmdSearchOutput(output, root, { docs: 'relative' }).length, 0);
  assert.equal(parseQmdSearchOutput('qmd://docs/../../secret.md', root).length, 0);
  fs.mkdirSync(path.join(external, 'excluded'));
  fs.writeFileSync(path.join(external, 'excluded', 'guide.md'), 'excluded zebra');
  fs.symlinkSync(base, path.join(external, 'escape'), 'junction');
  assert.equal(parseQmdSearchOutput('qmd://docs/escape/secret.md', root, mapping).length, 0);
  const script = path.join(base, 'mock.cjs');
  fs.writeFileSync(script, `console.log(process.argv[2] === 'search' ? ${JSON.stringify(output + '\nqmd://docs/excluded/guide.md')} : 'ready');`);
  fs.mkdirSync(path.join(root, '.qmd-adaptive-search'));
  const configPath = path.join(root, '.qmd-adaptive-search', 'config.json');
  const config = { qmdCommand: [process.execPath, script], collectionRoots: mapping, excludeGlobs: ['excluded/**'] };
  fs.writeFileSync(configPath, JSON.stringify(config));
  const result = adaptiveSearch({ query: 'zebra', mode: 'precision' }, { root, readOnly: true });
  assert.equal(result.results.length, 1);
  assert.equal(result.results[0].lead, 'external zebra documentation');
  assert.deepEqual(result.results[0].highlights, ['external zebra documentation']);
  fs.unlinkSync(path.join(root, 'guide.md'));
  assert.equal(parseQmdSearchOutput(output, root).length, 0);
});
